### ISSUE TITLE
What is a "sampling error" when placing something in something 

### ISSUE THREAD

**Issue by meier-johannes94** [StanfordVL/iGibson#146]
Hi, 
I am working with discrete action space and I try to place a hardbook in a container. I am getting the following: 
```
Object_id: 9, action_prim: 6
PRIMITIVE:attempt to place hardback_50 inside carton_57
PRIMITIVE: place hardback_50 inside carton_57 fail, sampling fail
PRIMITIVE satisfied predicates: {'satisfied': [], 'unsatisfied': [0]}
```
Why does placing fail? And what is a "sampling fail"? What can I do that it works?

**Comment by roberto-martinmartin** [comment]
Our given primitives will try to find a valid pose of object A to be in object B. if it is found, it will try to find a trajectory of the robot to bring the object A (I assume it is grasped) to that location.
if the sampling fails, it may be the sampling of object A in object B that is not possible for example because object A is bigger than object B (seems to not be the case) or the trajectory motion sampler that cannot find a good trajectory, for example, a collision free path is not found, or the arm cannot reach the goal. This is common in sampling based motion planning, there is not always a valid solution. The procedure and the sampling can be improved. Alternatively, the sampling-based primitives can be replaced by other solutions, analytic or learned.

Our motion primitives are just a starting point to generate solutions, not a solution by themselves. I would recommend going deeper into the code and improving or replacing them. Using them as black-box will not lead to very good performance, you would have to deal with multiple errors.

If you improve them, we would be very glad to incorporate them, just file a pull request.

The API for discrete actions will improve in the next weeks, but the implementation we provide with sampling-based planners will be very similar.

Thanks!
