### ISSUE TITLE
iGibson 1.0: Instance Segmentation (ins_seg)

### ISSUE THREAD

**Issue by rudrapoudel** [StanfordVL/iGibson#341]
Looking for a utility function or code to produce the instance segmentation on iGibson 1.0, similar to the ins_seg sensor output of the iGibson +2.0. Thanks!

**Comment by cgokmen** [comment]
Hi,

This functionality is not included out of the box in that version, but you can make the `seg` channel show an instance segmentation rather than a semantic segmentation by changing the below lines such that each object gets a unique ID rather than its class ID:

https://github.com/StanfordVL/iGibson/blob/555dc3da7782a75f50a98b50abccd6ba3d868bf3/igibson/simulator.py#L234-L235

This only affects objects loaded with the scene - for other objects imported via `import_object`, you can pass in an appropriate class ID via the class_id variable.

Please do let us know why you prefer iGibson 1.0 instead of the latest 2.0 so that we are aware of missing features etc.

Thanks!
