### ISSUE TITLE
ROS integration with husky robot 

### ISSUE THREAD

**Issue by skp1204** [StanfordVL/iGibson#39]
Hi,
I have ROS Melodic installed on my PC. I created the appropriate python, yaml and launch files following the turtlebot ROS integration. I am getting the following error while loading the URDF model ( using the same urdf  in the assets ). My launch file is as follows:

![Screenshot from 2020-06-02 11-39-31](https://user-images.githubusercontent.com/44667823/83499283-ce026f00-a4c5-11ea-9517-1f12055203d0.png)

![Screenshot from 2020-06-02 11-32-36](https://user-images.githubusercontent.com/44667823/83499316-df4b7b80-a4c5-11ea-8d81-283d50b74b79.png)

**Comment by roberto-martinmartin** [comment]
Hi!
I think the issue is with the environmental variables that could set the position and orientation of the IMU and that should receive a default value if not set.
Could you try setting environmental variables in /etc/ros/setup.bash with the name HUSKY_IMU_XYZ and HUSKY_IMU_RPY 
![image](https://user-images.githubusercontent.com/7702561/123885987-5d659600-d903-11eb-8bfd-2e18fc591dff.png)
![image](https://user-images.githubusercontent.com/7702561/123886242-e250af80-d903-11eb-8074-395440d09cac.png)
Feel free to reopen if this doesn't solve the issue
