### ISSUE TITLE
turtlebot_rgbd.py obs["depth"] always output depth data no more than 1 meter

### ISSUE THREAD

**Issue by JiatongBao** [StanfordVL/iGibson#46]
in gibson2-ros/turtlebot_rgbd.py,   depth = obs["depth"].astype(np.float32)  always output range data no more than 1 meter. I use the print(max(map(max,depth))) to output the maximum range.

Thus, the generated depth image (point cloud) and pseudo laser scan is very closed to the robot.

**Comment by fxia22** [comment]
This is because the environment is outputting normalized depth values, you would need to comment out the normalization part to get raw depth. https://github.com/StanfordVL/iGibson/blob/master/gibson2/envs/locomotor_env.py#L280-L293

@ChengshuLi, let's make this configurable via yaml file in the new release. Thanks!
