### ISSUE TITLE
What's the meaning of 'reward_type:geodesic' ?

### ISSUE THREAD

**Issue by ievn2015** [StanfordVL/iGibson#80]
Parameters of the config file for Environments are explained in the iGibson docs. 
I can check the 'potential_reward.py' and 'reaching_goal_reward.py' for details.
However, what's the meaning of 'reward_type:geodesic' in the iGibson docs? Can I try l2_reward_type or sparse_reward?

**Comment by fxia22** [comment]
There are multiple ways to provide reward for a point to point navigation task.
1. sparse reward: only reward the agent arrives at the target. 
2. l2 reward: reward the agent when it approach the target in l2 distance. 
3. geodesic reward: reward the agent when it approach the target in geodesic distance. 

Normally the geodesic distance makes more sense, since there will be obstacles in the environment. If the environment does not have any obstacles, l2 distance and geodesic distance are equivalent.
